### ISSUE TITLE
 Giveaway for xxx ended. No winner was found.

### ISSUE THREAD

**Issue by Skyrid3r** [shukriadams/discord-giveawaybot#11] opened 2018-05-28 08:08 UTC
Just 5min ago I noticed that a giveaway ended, but no winner was found.

I checked, and 7 participants joined it as you can see here:

> {"level":"info","message":"Of Darkest Dreams joined giveaway ID 56 - Daddy's gone a-hunting.","timestamp":"2018-05-28T07:31:00.298Z"}
> {"level":"info","message":"Ð¡C joined giveaway ID 56 - Daddy's gone a-hunting.","timestamp":"2018-05-28T07:34:10.320Z"}
> {"level":"info","message":"aiRoy17 joined giveaway ID 56 - Daddy's gone a-hunting.","timestamp":"2018-05-28T07:34:50.323Z"}
> {"level":"info","message":"oDku79 joined giveaway ID 56 - Daddy's gone a-hunting.","timestamp":"2018-05-28T07:36:00.331Z"}
> {"level":"info","message":"Master Kingz joined giveaway ID 56 - Daddy's gone a-hunting.","timestamp":"2018-05-28T07:38:50.353Z"}
> {"level":"info","message":"Deverz joined giveaway ID 56 - Daddy's gone a-hunting.","timestamp":"2018-05-28T07:48:30.412Z"}
> {"level":"info","message":"Giveaway closed - ID 56 - Daddy's gone a-hunting.","timestamp":"2018-05-28T08:00:50.668Z"}

When I attempted to reroll ID 56, I got the following:

> This giveaway has no participants, rerolling is not possible.

I checked the status of the system, not sure if related or because of attempting to reroll it.

> Mhàrt 28 10:02:31 tf2lottery giveaway[23298]: error:  DiscordAPIError: Unknown Member
> Mhàrt 28 10:02:31 tf2lottery giveaway[23298]:     at item.request.gen.end (/home/skyrider/discord/giveaway/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
> Mhàrt 28 10:02:31 tf2lottery giveaway[23298]:     at then (/home/skyrider/discord/giveaway/node_modules/snekfetch/src/index.js:215:21)
> Mhàrt 28 10:02:31 tf2lottery giveaway[23298]:     at <anonymous>
> Mhàrt 28 10:02:31 tf2lottery giveaway[23298]:     at process._tickCallback (internal/process/next_tick.js:188:7)
> Mhàrt 28 10:02:45 tf2lottery giveaway[23298]: error:  DiscordAPIError: Unknown Member
> Mhàrt 28 10:02:45 tf2lottery giveaway[23298]:     at item.request.gen.end (/home/skyrider/discord/giveaway/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
> Mhàrt 28 10:02:45 tf2lottery giveaway[23298]:     at then (/home/skyrider/discord/giveaway/node_modules/snekfetch/src/index.js:215:21)
> Mhàrt 28 10:02:45 tf2lottery giveaway[23298]:     at <anonymous>
> Mhàrt 28 10:02:45 tf2lottery giveaway[23298]:     at process._tickCallback (internal/process/next_tick.js:188:7)

^ As the above is 2min later and it ended at exactly 10:00 with a few seconds later.

Maybe? This is related to my 4 Hours restart every time, but I am not sure. Last restart was at 10:00:28

Maybe this 'messed' up the bit at the same time of the restart. Maybe something to include later on as a feature to prevent this.

**Comment by Skyrid3r** [comment] 2018-05-28 21:26
Just happened again today:

> Shenron: Giveaway for Doorways: The Underworld ended.No winner was found.

**Comment by shukriadams** [comment] 2018-09-16 20:45
I'm assuming this issue was resolved by 0.1.7, and was caused by me polling participants from discord with an unreliable API call. If you experience this issue again, feel free to reopen the ticket.

**Closed by shukriadams** 2018-09-16 20:45 UTC
Labels: bug
